---
- name: Clone the prelude emacs configs
  become: True
  become_user: "{{ lookup('env', 'USER') }}"
  git:
    repo: "git@github.com:mklvr/prelude.git"
    dest: "{{ lookup('env', 'HOME') }}/Projects/mklvr/prelude"
    clone: True
    update: True
    force: True

- name: Create and .emacs.d directory
  file:
    dest: "{{ lookup('env', 'HOME') }}/.emacs.d"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  when: ansible_distribution != "openSUSE Leap"

- name: Create and .emacs.d directory
  file:
    dest: "{{ lookup('env', 'HOME') }}/.emacs.d"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: users
  when: ansible_distribution == "openSUSE Leap"

- name: Stow the emacs configs
  command: stow -d {{ lookup('env', 'HOME') }}/Projects/mklvr/prelude -t {{ lookup('env', 'HOME') }}/.emacs.d ./

- name: Make sure our user systemd directory exists
  file:
    dest: "{{ lookup('env', 'HOME') }}/.config/systemd"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  when: ansible_distribution != "openSUSE Leap"

- name: Create the user systemd service file
  copy:
    src: emacs.service
    dest: "{{ lookup('env', 'HOME') }}/.config/systemd/emacs.service"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  when: ansible_distribution != "openSUSE Leap"

- name: Enable the emacs service
  become: no
  systemd:
    name: emacs
    state: started
    enabled: True
    scope: user

- name: Create a new application object for emacsclient
  copy:
    src: emacsclient.desktop
    dest: "{{ lookup('env', 'HOME') }}/.local/share/applications/emacsclient.desktop"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  when: ansible_distribution != "openSUSE Leap"
