---
- name: Get everything up to date
  apt: name=* state=latest update_cache=True

- name: Install desired packages
  apt: name="{{ base_packages }}" state=present

- name: enable some of the installed services
  service: name="{{ item }}" state=started enabled=True
  with_items: "{{ base_services }}"

- name: Add the user to groups for services
  user:
    name: "{{ lookup('ENV', 'USER') }}"
    shell: /bin/zsh
    groups: docker,libvirt
    append: True

- name: Install some classic snaps
  snap: name="{{ snap_packages.classic }}" state=present classic=True

- name: Install some default snaps
  snap: name="{{ snap_packages.default }}" state=present

- include_tasks: brave.yml
  when: install_brave | bool

- name: Add github to known_hosts
  lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: Clone the prelude emacs configs
  become: True
  become_user: "{{ lookup('env', 'USER') }}"
  git:
    repo: "git@github.com:mklvr/prelude.git"
    dest: "{{ lookup('env', 'HOME') }}/Projects/mklvr/prelude"
    clone: True
    update: True
    force: True

- name: Create and .emacs.d directory
  file:
    dest: "{{ lookup('env', 'HOME') }}/.emacs.d"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"

- name: Stow the emacs configs
  command: stow -d {{ lookup('env', 'HOME') }}/Projects/mklvr/prelude -t {{ lookup('env', 'HOME') }}/.emacs.d ./
