---
- include_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'

- include_tasks: debian.yml
  when: ansible_distribution == 'Debian'

- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
