---
- include_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'

- include_tasks: opensuse.yml
  when: ansible_distribution == "openSUSE Leap" or ansible_distribution == "openSUSE Tumbleweed"

- include_tasks: debian.yml
  when: ansible_distribution == 'Debian'

- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS'
- name: Allow regular users to run dmesg
  ansible.builtin.sysctl:
    name: kernel.dmesg_restrict
    value: 0
    state: present
    reload: yes
  become: True
