---
- name: Ensure the bin directory exists in our users home directory
  become_user: "{{ lookup('env', 'USER') }}"
  file:
    dest: "{{ lookup('env', 'HOME') }}/bin"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: 0755
  when: ansible_distribution != "openSUSE Leap"

- name: Ensure the bin directory exists in our users home directory
  become_user: "{{ lookup('env', 'USER') }}"
  file:
    dest: "{{ lookup('env', 'HOME') }}/bin"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: users
    mode: 0755
  when: ansible_distribution == "openSUSE Leap"

- name: Download stern
  become_user: "{{ lookup('env', 'USER') }}"
  ansible.builtin.get_url:
    url: https://github.com/stern/stern/releases/download/v1.31.0/stern_1.31.0_linux_amd64.tar.gz
    dest: "/tmp/stern.tar.gz"

- name: Decompress the downloaded file
  ansible.builtin.unarchive:
    src: "/tmp/stern.tar.gz"
    dest: "/tmp/"

- name: Copy stern to bin
  ansible.builtin.copy:
    src: /tmp/stern
    dest: /usr/local/bin/stern
    remote_src: true
    mode: 0755
    owner: root
    group: root
  become: true
