# If you come from bash you might have to change your $PATH.
export PATH=$HOME/.local/bin:$HOME/bin:/usr/local/bin:/opt/chefdk/bin:/opt/inspec/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/home/$USER/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="lambda"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  sudo
  docker
  golang
  yum
  pass
)

[  -f $ZSH/oh-my-zsh.sh ] && source $ZSH/oh-my-zsh.sh

# Get the FZF key bindings and set the search paths
[ -f /usr/share/doc/fzf/examples/key-bindings.zsh ] && source /usr/share/doc/fzf/examples/key-bindings.zsh
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git --exclude Downloads --exclude perl5 --exclude ISO --exclude VM --exclude Library --exclude .tmp --exclude .backups --exclude Mail --exclude News --exclude snap'

# If we have dircolors sets, use them
[ -f ~/.dircolors ] && eval $(dircolors -b ~/.dircolors)

# For systemd user service
export XDG_RUNTIME_DIR=/run/user/`id -u`

# Look for some snapd path stuff and load it if found
[ -f /etc/profile.d/snapd.sh ] && emulate sh -c 'source /etc/profile.d/snapd.sh'
[ -f /etc/profile.d/apps-bin-path.sh ] && emulate sh -c 'source /etc/profile.d/apps-bin-path.sh'

# Use lastpass with FZF
lastpass_fzf () {
    lpass show -c --password $(lpass ls  | fzf | awk '{print $(NF)}' | sed 's/\]//g')
}
zle -N lastpass_fzf
bindkey '^X^l' lastpass_fzf

# Configure bat as a pager
export BAT_THEME="Monokai Extended Light"
export BAT_PAGER=never

alias apt-uu="sudo apt update; sudo apt upgrade -y"
alias gssh='gcloud alpha cloud-shell ssh'
